### ISSUE TITLE
Insufficient A100 memory for overly long context.

### ISSUE THREAD

**Issue by cuiwenyao** [bigai-nlco/LooGLE#1]
Thank you for your outstanding work, but I encountered the following problem during testing.
The single A100 (80GB) card has insufficient memory when predicting with overly long context. I am very curious how you solve this tricky problem.
I saw in your code:
```python
if len(tokenized_prompt) > max_length:
    half = int(max_length/2)
    prompt = tokenizer.decode(tokenized_prompt[:half], skip_special_tokens=True) + tokenizer.decode(tokenized_prompt[-half:], skip_special_tokens=True)
```
Does this approach affect the accuracy of the evaluation?
Thank you again.

**Comment by lijiaqijane** [comment]
Thanks for your comments. For the OOM problem, we recommend you to use flash-attention for acceleration. 
The code you refer is the truncation strategy we used in this paper. It is only for cases whose inputs length is larger than the limited context window size of the test model.
