### ISSUE TITLE
groundtruth逻辑是否有问题

### ISSUE THREAD

**Issue by Duandand** [bigai-nlco/LooGLE#5]
你好，在pred_gpt_models.py中get_pre()方法是否有bug？

def get_pred(model, data_instance, tokenizer, max_length, max_gen, prompt_format, device):

    ans, groundtruth = [], []
    preds = {}
    raw_inputs = data_instance['input']
    if data_instance['qa_pairs'] == 'none':
        preds['qa_pairs'] = data_instance['qa_pairs']
        json_obj = {'input': raw_inputs}

        prompt = prompt_format.format(**json_obj)
        tokenized_prompt = tokenizer(prompt, truncation=False, return_tensors="pt").input_ids[0]
        if len(tokenized_prompt) > max_length:
            half = int(max_length/2)
            prompt = tokenizer.decode(tokenized_prompt[:half], skip_special_tokens=True)+tokenizer.decode(tokenized_prompt[-half:], skip_special_tokens=True)
        
        
        input_ids = tokenizer(prompt, truncation=True, return_tensors="pt").input_ids.to(device)
        context_length = input_ids.shape[-1]
        with torch.no_grad():
            output = model.generate(input_ids,max_new_tokens=max_gen,temperature=1.0,num_beams=1,do_sample=False,repetition_penalty=float(2))[0]
        pred = tokenizer.decode(output[context_length:], skip_special_tokens=True)

        ans.append(pred)
        groundtruth.append(raw_inputs)

这里的groundtruth怎么是raw_inputs？

**Comment by lijiaqijane** [comment]
Thanks for your kind reminder.  🫡
We have already fixed this little mistake in line 74  from "groundtruth.append(raw_inputs)" to "groundtruth.append(data_instance["output"])".
